def format_sudoku_string(sudoku_string):
    """
    This is, admittedly, a silly function. However, it's needed to make a sudoku represented as a
    string shown correctly in the css-grid. Avoiding this format function would require a larger refactoring
    of either the HTML/CSS-structure or the backend-sudoku-solver
    """
    new_string = ""
    new_string += sudoku_string[0]
    new_string += sudoku_string[1]
    new_string += sudoku_string[2]
    new_string += sudoku_string[9]
    new_string += sudoku_string[10]
    new_string += sudoku_string[11]
    new_string += sudoku_string[18]
    new_string += sudoku_string[19]
    new_string += sudoku_string[20]

    new_string +=  sudoku_string[3]
    new_string += sudoku_string[4]
    new_string += sudoku_string[5]
    new_string += sudoku_string[12]
    new_string += sudoku_string[13]
    new_string += sudoku_string[14]
    new_string += sudoku_string[21]
    new_string += sudoku_string[22]
    new_string += sudoku_string[23]

    new_string += sudoku_string[6]
    new_string += sudoku_string[7]
    new_string += sudoku_string[8]
    new_string += sudoku_string[15]
    new_string += sudoku_string[16]
    new_string += sudoku_string[17]
    new_string += sudoku_string[24]
    new_string += sudoku_string[25]
    new_string += sudoku_string[26]

    new_string += sudoku_string[27]
    new_string += sudoku_string[28]
    new_string += sudoku_string[29]
    new_string += sudoku_string[36]
    new_string += sudoku_string[37]
    new_string += sudoku_string[38]
    new_string += sudoku_string[45]
    new_string += sudoku_string[46]
    new_string += sudoku_string[47]

    new_string +=  sudoku_string[30]
    new_string += sudoku_string[31]
    new_string += sudoku_string[32]
    new_string += sudoku_string[39]
    new_string += sudoku_string[40]
    new_string += sudoku_string[41]
    new_string += sudoku_string[48]
    new_string += sudoku_string[49]
    new_string += sudoku_string[50]

    new_string += sudoku_string[33]
    new_string += sudoku_string[34]
    new_string += sudoku_string[35]
    new_string += sudoku_string[42]
    new_string += sudoku_string[43]
    new_string += sudoku_string[44]
    new_string += sudoku_string[51]
    new_string += sudoku_string[52]
    new_string += sudoku_string[53]
    
    new_string += sudoku_string[54]
    new_string += sudoku_string[55]
    new_string += sudoku_string[56]
    new_string += sudoku_string[63]
    new_string += sudoku_string[64]
    new_string += sudoku_string[65]
    new_string += sudoku_string[72]
    new_string += sudoku_string[72]
    new_string += sudoku_string[74]
    
    new_string +=  sudoku_string[57]
    new_string += sudoku_string[58]
    new_string += sudoku_string[59]
    new_string += sudoku_string[66]
    new_string += sudoku_string[67]
    new_string += sudoku_string[68]
    new_string += sudoku_string[75]
    new_string += sudoku_string[76]
    new_string += sudoku_string[77]

    new_string += sudoku_string[60]
    new_string += sudoku_string[61]
    new_string += sudoku_string[61]
    new_string += sudoku_string[69]
    new_string += sudoku_string[70]
    new_string += sudoku_string[71]
    new_string += sudoku_string[78]
    new_string += sudoku_string[79]
    new_string += sudoku_string[80]
    
    return new_string